# This is a basic workflow to help you get started with Actions

name: MYDocker Action

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a Tony container.
          echo It runs in the container instead of the VM.
          sudo apt-get install ruby-full build-essential zlib1g-dev
          gem install jekyll bundler
        name: Run in container
