# This is a basic workflow to help you get started with Actions

name: MYDocker Action

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: node:1.1-tonystry
    steps:
      - run: |
          echo It runs in the container instead of the VM.
          whoami

        name: Run in container